
name: Eleventy Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.1.0
      with: 
        fetch-depth: 2
    - name: Eleventy Build
      uses: TartanLlama/actions-eleventy@v1.2
      with:
        install_dependencies: true      
    - name: Deploy
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ftp://ftp.floriade.co.nz/public_html/eleventy/
        ftp-username: geoff@floriade.co.nz
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: _site
        git-ftp-args: --dry-run
