
name: Eleventy Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Eleventy Build
      uses: TartanLlama/actions-eleventy@v1.2
      with:
        install_dependencies: true      
